# Generated by Django 4.1.5 on 2023-09-12 18:25

import Stage2App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage2App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, validators=[Stage2App.models.validate_name_is_string]),
        ),
    ]
